# NSS-NDR 凭据（部署前必须修改）
# 生成随机密码示例：
#   openssl rand -hex 16
# 然后把下面的 CHANGE_ME_* 替换后 apply，或改用：
#   kubectl -n nss-ndr create secret generic nss-ndr-secrets --from-literal=elastic-password=... ...
apiVersion: v1
kind: Secret
metadata:
  name: nss-ndr-secrets
  namespace: nss-ndr
type: Opaque
stringData:
  elastic-password: "nss-ndr@2026"
  filebeat-password: 3f0b8df0a1aa02fa2d6f1c18ff402eb5
  kibana-password: 2579393fdb831ae01097741f4e4035cd
  kibana-encryption-key: a81faa205fd9a47e8f771d5c76cbe6c856d47f8b98242d286ca65ef4596e6966
  kibana-encrypted-saved-objects-key: 3ce572abe2914722db05c6b3f3de3140478be071b04c62266fad6594646badbe
  kibana-reporting-key: 5085d04888b1435635753146b12d420d6260a3ecfcecb87b420ad436d9edde54
  xdr-push-password: 32c1fcc8abe874a2d00d2225d9790fd0
  redis-password: 038ccacf3bce5cb0ca6606194823eeca
