apiVersion: apps/v1
kind: Deployment
metadata:
  name: nss-kibana
  namespace: nss-ndr
  labels:
    app: nss-kibana
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nss-kibana
  template:
    metadata:
      labels:
        app: nss-kibana
    spec:
      containers:
        - name: kibana
          image: ghcr.io/cxiyuan/nss-ndr/nss-ndr-kibana
          imagePullPolicy: IfNotPresent
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://nss-elasticsearch:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nss-ndr-secrets
                  key: kibana-password
          ports:
            - containerPort: 5601
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nss-kibana
  namespace: nss-ndr
spec:
  type: NodePort
  selector:
    app: nss-kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30601
