apiVersion: apps/v1
kind: Deployment
metadata:
  name: nss-logstash
  namespace: nss-ndr
  labels:
    app: nss-logstash
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nss-logstash
  template:
    metadata:
      labels:
        app: nss-logstash
    spec:
      containers:
        - name: logstash
          image: ghcr.io/cxiyuan/nss-ndr/nss-ndr-logstash
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: "nss-redis"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nss-ndr-secrets
                  key: redis-password
            - name: ES_HOST
              value: "http://nss-elasticsearch:9200"
            - name: ES_USERNAME
              value: "xdr-push"
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nss-ndr-secrets
                  key: xdr-push-password
          ports:
            - containerPort: 5055
            - containerPort: 9600
          volumeMounts:
            - name: certs
              mountPath: /usr/share/logstash/certs
              readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 2Gi
      volumes:
        - name: certs
          secret:
            secretName: nss-ndr-certs
---
apiVersion: v1
kind: Service
metadata:
  name: nss-logstash
  namespace: nss-ndr
spec:
  selector:
    app: nss-logstash
  ports:
    - name: beats
      port: 5055
      targetPort: 5055
    - name: api
      port: 9600
      targetPort: 9600
