apiVersion: apps/v1
kind: Deployment
metadata:
  name: nss-redis
  namespace: nss-ndr
  labels:
    app: nss-redis
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nss-redis
  template:
    metadata:
      labels:
        app: nss-redis
    spec:
      containers:
        - name: redis
          image: docker.io/library/redis:7-alpine
          imagePullPolicy: IfNotPresent
          args:
            - "redis-server"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
            - "--maxmemory"
            - "256mb"
            - "--maxmemory-policy"
            - "allkeys-lru"
            - "--appendonly"
            - "yes"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nss-ndr-secrets
                  key: redis-password
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nss-redis
  namespace: nss-ndr
spec:
  selector:
    app: nss-redis
  ports:
    - port: 6379
      targetPort: 6379
