# NSS-NDR Kibana 配置

server.host: "0.0.0.0"
server.port: 5601

elasticsearch.hosts: ["https://nss-elasticsearch:9200"]
elasticsearch.ssl.verificationMode: none
elasticsearch.username: "${ES_USERNAME:}"
elasticsearch.password: "${ES_PASSWORD:}"

logging.root.level: info
