apiVersion: v1
kind: ConfigMap
metadata:
  name: nss-ndr-config
  namespace: {{ .Release.Namespace }}
data:
  probe.yaml: |
{{ toYaml .Values.probeConfig | indent 4 }}
  suricata.yaml: |
{{ include "nss.render" (dict "ctx" . "file" "configs/suricata.yaml") | indent 4 }}
  threshold.conf: |
{{ .Files.Get "configs/threshold.conf" | indent 4 }}
  local.zeek: |
{{ .Files.Get "configs/local.zeek" | indent 4 }}
  node.cfg: |
{{ include "nss.render" (dict "ctx" . "file" "configs/node.cfg") | indent 4 }}
  zeekctl.cfg: |
{{ include "nss.render" (dict "ctx" . "file" "configs/zeekctl.cfg") | indent 4 }}
  networks.cfg: |
{{ include "nss.render" (dict "ctx" . "file" "configs/networks.cfg") | indent 4 }}
  filebeat.yml: |
{{ .Files.Get "configs/filebeat.yml" | indent 4 }}
  kibana.yml: |
{{ .Files.Get "configs/kibana.yml" | indent 4 }}
  bpf: |
{{ .Values.probeConfig.probe.bpf | indent 4 }}
  sensor_id: {{ .Values.probeConfig.probe.id }}
  interface: {{ .Values.probeConfig.probe.interface }}
  all-rulesets.rules: ""
{{- range $path, $_ := .Files.Glob "configs/policy/**" }}
  {{ $path | trimPrefix "configs/" }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
