apiVersion: v1
kind: ConfigMap
metadata:
  name: nss-ndr-config
  namespace: {{ .Release.Namespace }}
data:
  probe.yaml: |
{{ toYaml .Values.probeConfig | indent 4 }}
  suricata.yaml: |
{{ include "nss.render" (dict "ctx" . "file" "configs/suricata.yaml") | indent 4 }}
  threshold.conf: |
{{ .Files.Get "configs/threshold.conf" | indent 4 }}
  local.zeek: |
{{ .Files.Get "configs/local.zeek" | indent 4 }}
  node.cfg: |
{{ include "nss.render" (dict "ctx" . "file" "configs/node.cfg") | indent 4 }}
  zeekctl.cfg: |
{{ include "nss.render" (dict "ctx" . "file" "configs/zeekctl.cfg") | indent 4 }}
  networks.cfg: |
{{ include "nss.render" (dict "ctx" . "file" "configs/networks.cfg") | indent 4 }}
  config.zeek: |
{{ .Files.Get "configs/config.zeek" | indent 4 }}
  filebeat.yml: |
{{ .Files.Get "configs/filebeat.yml" | indent 4 }}
  strelka_backend.yaml: |
{{ .Files.Get "configs/strelka/backend.yaml" | indent 4 }}
  strelka_logging.yaml: |
{{ .Files.Get "configs/strelka/logging.yaml" | indent 4 }}
  strelka_passwords_dat: |
{{ .Files.Get "configs/strelka/passwords.dat" | indent 4 }}
  strelka_taste_yara: |
{{ .Files.Get "configs/strelka/taste/taste.yara" | indent 4 }}
  strelka_frontend.yaml: |
{{ .Files.Get "configs/strelka/frontend.yaml" | indent 4 }}
  strelka_filestream.yaml: |
{{ .Files.Get "configs/strelka/filestream.yaml" | indent 4 }}
  strelka_manager.yaml: |
{{ .Files.Get "configs/strelka/manager.yaml" | indent 4 }}
  bpf: |
{{ .Values.probeConfig.probe.bpf | indent 4 }}
  sensor_id: {{ .Values.probeConfig.probe.id }}
  interface: {{ .Values.probeConfig.probe.interface }}
  all-rulesets.rules: ""
{{- range $path, $_ := .Files.Glob "configs/policy/**" }}
  {{ $path | trimPrefix "configs/" | replace "/" "_" }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
