apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nss-ndr-nsm
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nss-ndr-es-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 200Gi
