apiVersion: v1
kind: Secret
metadata:
  name: nss-ndr-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  elastic-password: {{ .Values.secrets.elastic }}
  filebeat-password: {{ .Values.secrets.filebeat }}
  xdr-push-password: {{ .Values.secrets.xdrPush }}
