apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nss-filebeat
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: {app: nss-filebeat}
  template:
    metadata:
      labels: {app: nss-filebeat}
    spec:
      tolerations: [{operator: Exists}]
      imagePullSecrets: {{ toYaml .Values.images.pullSecrets | nindent 8 }}
      containers:
        - name: filebeat
          image: "{{ .Values.images.registry }}/nss-ndr-filebeat:{{ .Values.images.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - {name: ES_HOST, value: "https://nss-elasticsearch:9200"}
            - {name: ES_USERNAME, value: "filebeat"}
            - name: ES_PASSWORD
              valueFrom: {secretKeyRef: {name: nss-ndr-secrets, key: filebeat-password}}
          volumeMounts:
            - {name: config, mountPath: /usr/share/filebeat/filebeat.yml, subPath: filebeat.yml, readOnly: true}
            - {name: nsm, mountPath: /nsm, readOnly: true}
            - {name: data, mountPath: /usr/share/filebeat/data}
      volumes:
        - {name: config, configMap: {name: nss-ndr-config}}
        - {name: nsm, persistentVolumeClaim: {claimName: nss-ndr-nsm}}
        - {name: data, emptyDir: {}}
